[package]
edition = "2021"
name = "bgtask_creator"
publish = false
version = "0.1.0"

[dependencies]
cadence = {workspace = true}
cadence-macros = {workspace = true}
chrono = {workspace = true}
clap = {workspace = true}
digital_asset_types = {workspace = true}
futures = {workspace = true}
log = {workspace = true}
nft_ingester = {workspace = true}
sea-orm = {workspace = true}
sea-query = {workspace = true}
solana-sdk = {workspace = true}
sqlx = {workspace = true}
tokio = {workspace = true}
