[package]
edition = "2021"
name = "mint_backfill"
publish = false
version = "0.0.1"

[dependencies]
acc_backfill = {path = "../acc_backfill"}
anyhow = {workspace = true}
async-stream = {workspace = true}
clap = {workspace = true}
futures = {workspace = true}
log = {workspace = true}
nft_ingester = {workspace = true}
solana-client = {workspace = true}
solana-commitment-config = {workspace = true}
solana-sdk = {workspace = true}
tokio = {workspace = true}
