[package]
authors = ["Helius"]
description = "Merkle tree utility tools. Forked from Triton and enriched with new features."
edition = "2021"
name = "tree_status"
publish = false
version = "0.1.0"

[dependencies]
anchor-client = {workspace = true}
anchor-lang = {workspace = true}
anyhow = {workspace = true}
bs58 = {workspace = true}
clap = {workspace = true}
crossbeam = {workspace = true}
digital_asset_types = {workspace = true}
env_logger = {workspace = true}
figment = {workspace = true}
flatbuffers = {workspace = true}
futures = {workspace = true}
hex = {workspace = true}
log = {workspace = true}
plerkle_messenger = {workspace = true}
plerkle_serialization = {workspace = true}
sea-orm = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
solana-client = {workspace = true}
solana-sdk = {workspace = true}
solana-transaction-status = {workspace = true}
mpl-account-compression = {workspace = true}
mpl-noop = {workspace = true}
solana-commitment-config = {workspace = true}
sqlx = {workspace = true}
thiserror = {workspace = true}
tokio = {workspace = true}
txn_forwarder = {workspace = true}
