[package]
name = "das-core"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
sqlx = { workspace = true }
cadence = { workspace = true }
cadence-macros = { workspace = true }

[lints]
workspace = true
