[package]
edition = "2021"
name = "txn_forwarder"
publish = false
version = "0.6.9"

[dependencies]
anyhow = {workspace = true}
clap = {workspace = true}
env_logger = {workspace = true}
figment = {workspace = true}
flatbuffers = {workspace = true}
futures = {workspace = true}
log = {workspace = true}
plerkle_messenger = {workspace = true}
plerkle_serialization = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
solana-client = {workspace = true}
solana-commitment-config = {workspace = true}
solana-sdk = {workspace = true}
solana-transaction-status = {workspace = true}
thiserror = {workspace = true}
tokio = {workspace = true}
tokio-stream = {workspace = true}
